###
# Insert - Brock Unit
###
POST http://localhost:3000/blockunits
Content-Type: application/json

{
    "block": 43,
    "unit": 11,
    "status": 1
}

###
# Get All - Brock Unit  
###
GET http://localhost:3000/blockunits

