version: '3'

services:

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    entrypoint: ./.docker/entrypoint.sh
    container_name: frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 8080:80
    volumes:
      - .:/home/node/app
