version: '3'

services:

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: ./.docker/entrypoint.sh
    container_name: frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
